package model;

import javafx.scene.chart.CategoryAxis;
import javafx.scene.chart.LineChart;
import javafx.scene.chart.NumberAxis;
import javafx.scene.chart.XYChart;

import java.util.ArrayList;

/**
 * Created by Sarosi on 26/11/2016.
 */
public class ChartBuillder {
    public ChartBuillder(){

    }

    /**
     * this method takes the data generated by Arraybuilder and constructs a chart based on it
     * @param dataArray county code, data and year sorted grouped by country and then by year
     * @return a Linechart object representing our data
     */
    public  static LineChart<String,Number> buildLineChart(ArrayList<ArrayList<DataPiece>> dataArray) {

        final CategoryAxis xAxis = new CategoryAxis();
        final NumberAxis yAxis = new NumberAxis();
        xAxis.setLabel("Year");
        yAxis.setLabel(dataArray.get(0).get(0).getIndicator());
        final LineChart<String,Number> lineChart =
                new LineChart<String,Number>(xAxis,yAxis);

        ArrayList<XYChart.Series> SerialKiller = new ArrayList<XYChart.Series>();


        for (int q = 0; q < dataArray.size(); q++) {
            SerialKiller.add(new XYChart.Series());
            SerialKiller.get(q).setName(dataArray.get(q).get(0).getCountry());

            for (int i = 0; i < dataArray.get(q).size(); i++) {
                System.out.println(SerialKiller.get(q).getName());
                SerialKiller.get(q).getData().add(new XYChart.Data(dataArray.get(q).get(i).getYear(), Double.parseDouble(dataArray.get(q).get(i).getValue())));
            }

            lineChart.getData().add(SerialKiller.get(q));

        }

        return lineChart;




    }

}
